// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh8cWYC6AzFGoYH7Rov8KxzpJ8DEpfMRk',
    appId: '1:791301072525:web:0c0619a81b9ef3ea6164c4',
    messagingSenderId: '791301072525',
    projectId: 'fitark',
    authDomain: 'fitark.firebaseapp.com',
    storageBucket: 'fitark.firebasestorage.app',
    measurementId: 'G-ZW18XZG7Z3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHx_VMrfY91qqNXq_tc6msUdtwdcdeqGo',
    appId: '1:791301072525:android:fa230da4f0e1ec3c6164c4',
    messagingSenderId: '791301072525',
    projectId: 'fitark',
    storageBucket: 'fitark.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdGKqkRfhjxKfSdEsH_vD5puL7zjNIfFM',
    appId: '1:791301072525:ios:cb9522f4eacc782f6164c4',
    messagingSenderId: '791301072525',
    projectId: 'fitark',
    storageBucket: 'fitark.firebasestorage.app',
    androidClientId: '791301072525-2bpk8l1vv1tn86b482vodnp8coqmq2so.apps.googleusercontent.com',
    iosClientId: '791301072525-plul2p1as0tb2jj6rvr4d86qea39q9kq.apps.googleusercontent.com',
    iosBundleId: 'dev.dwikiy.fitark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdGKqkRfhjxKfSdEsH_vD5puL7zjNIfFM',
    appId: '1:791301072525:ios:cb9522f4eacc782f6164c4',
    messagingSenderId: '791301072525',
    projectId: 'fitark',
    storageBucket: 'fitark.firebasestorage.app',
    androidClientId: '791301072525-2bpk8l1vv1tn86b482vodnp8coqmq2so.apps.googleusercontent.com',
    iosClientId: '791301072525-plul2p1as0tb2jj6rvr4d86qea39q9kq.apps.googleusercontent.com',
    iosBundleId: 'dev.dwikiy.fitark',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh8cWYC6AzFGoYH7Rov8KxzpJ8DEpfMRk',
    appId: '1:791301072525:web:df1a6adf888bdbd76164c4',
    messagingSenderId: '791301072525',
    projectId: 'fitark',
    authDomain: 'fitark.firebaseapp.com',
    storageBucket: 'fitark.firebasestorage.app',
    measurementId: 'G-VXLMC9R05X',
  );

}